/myparams:
  ros__parameters:
    ang_vel: 0.7476
    controller:
    - 0.5
    - 0.7
    - 1000.0
    label_str: Hola mundo
    lin_vel: 0.117
    param_int: 65
    timer_period: 0.01
    use_sim_time: false

