controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    dofbot_controller:
      type: forward_command_controller/ForwardCommandController


    gripper_controller:
      type: forward_command_controller/ForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

dofbot_controller:
  ros__parameters:
    joints:
      - arm_joint_01
      - arm_joint_02
      - arm_joint_03
      - arm_joint_04
      - arm_joint_05
      #- grip_joint
    interface_name: position
gripper_controller:
  ros__parameters:
    joints:
      - grip_joint
      - rfinger_joint_01
      - rfinger_joint_02
      - lfinger_grip_joint_01
      - lfinger_grip_joint_02
      - lfinger_grip_joint_03
    interface_name: position